### ISSUE TITLE
Remove my contributions

### ISSUE THREAD

**Issue by siliconedevelopment** [Pcola129/ahgoverhaul#1]
Seeing as you removed me from the mod, I demand you remove my contributions since I do not allow you to use my work.

**Comment by ainsleyblyat** [comment]
wtf you gay

also consider it done

**Comment by siliconedevelopment** [comment]
> wtf you gay
> 
> also consider it done

For one I did not agree to the "Contributor Policy Notice" and it was created _after_ I was removed from the development team. If you do not remove my contributions when the next update comes out I'll be looking into filing a DMCA against the mod.

**Comment by Pcola129** [comment]
Your content will be removed by the end of Saturday.

**Comment by Pcola129** [comment]
Your contributions have been removed. Issues resolved.
