### ISSUE TITLE
Issue not resolved.

### ISSUE THREAD

**Issue by siliconedevelopment** [Pcola129/ahgoverhaul#2]
The states I made are still on there. That was still my work and I request for them to also be removed.

**Comment by Pcola129** [comment]
The states you made were removed and replaced with states that I added myself. If you notice the manpower and buildings are different.

**Comment by siliconedevelopment** [comment]
I looked at the contributions and they are the same except the manpower and buildings are different.

**Comment by generalisofficial** [comment]
Kids, this work isnt anything that requires actual effort to do, just drop this

**Comment by snoekbaars** [comment]
It smell like updog in here

**Comment by Pcola129** [comment]
settlement reached off github. issue closed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
