### ISSUE TITLE
Duplicate country tag - Kentucky & Kanto

### ISSUE THREAD

**Issue by KyleGoetke** [Pcola129/ahgoverhaul#21]
In HGO_countries_l_english.yml, both Kentucky (line ~9160) and Kanto (line ~19720) have the tag KNT. This results in Kanto being the name for both released nations. (version 1.9.3)

**Comment by Gaffate** [comment]
Pretty sure this has been fixed. did you have the latest version?

**Comment by KyleGoetke** [comment]
I thought so but I actually had an old version enabled. My apologies
