### ISSUE TITLE
(for Skylar)

### ISSUE THREAD

**Issue by siliconedevelopment** [Pcola129/ahgoverhaul#3]
You gave me permission to use the mod for one of my mods, is that still in effect?
If I am still allowed, I am planning to use the following:
States (that obv includes provinces)
Localisation

If you want me to change anything up for my mod, I will do at your request.

**Comment by generalisofficial** [comment]
A bit cringe to demand your own work removed from hgo and then ask if you can still use hgo

**Comment by Pcola129** [comment]
Yeah, that’s still fine. As long as you credit our mod and post a workshop link on the steam workshop page, you’re still free to use HGO for your mod.
