### ISSUE TITLE
How'd you remove the HOI4 logo at the top of the screen whilst in a game (the giant billboard thing)

### ISSUE THREAD

**Issue by siliconedevelopment** [Pcola129/ahgoverhaul#5]
I really dont care about the past anymore, you did stuff, I did stuff, lets just move on. Anyway, how did you remove it since I could not get it to work for my mod.

**Comment by Pcola129** [comment]
I just replaced the logo_game.dds asset with the hgo logo and repositioned it. Fairly simple stuff really.

**Comment by siliconedevelopment** [comment]
I meant the big thing in-game (you know at the top of the map that says Hearts of Iron IV)

**Comment by Pcola129** [comment]
i just replaced the asset for it with a blank texture.
