### ISSUE TITLE
Divide the oceans

### ISSUE THREAD

**Issue by playableparable123** [Pcola129/ahgoverhaul#7]
If I want let's say Bermuda to own some ocean around it I don't want it to own 90% of all the ocean fix it

**Comment by alextheobserver2019** [comment]
O_O hmmm idk what to say but i didn't understood and i am confused

**Comment by playableparable123** [comment]
Let's say I want to give the bay area to the us and just the bay the bay is part of a big state that spans the entire Pacific

**Comment by alextheobserver2019** [comment]
you mean the territorial waters?

**Comment by playableparable123** [comment]
The ocean are land and they are in a ocean nation

**Comment by alextheobserver2019** [comment]
i don't understand but it's interesting
i have 3 possibilities what you meant by this:
A: Territorial Waters
B: Land Reclamation
C: i don't understand anything

**Comment by playableparable123** [comment]
B

**Comment by playableparable123** [comment]
I'm talking about the GitHub version

**Comment by alextheobserver2019** [comment]
eh ok let's continue tomorrow

**Comment by Pcola129** [comment]
noted. will consider.
