### ISSUE TITLE
Creating floodzones

### ISSUE THREAD

**Issue by fleeingmoth** [Pcola129/ahgoverhaul#9]
Just like there are reclamation zones and Atlantropa, there should be the same going the opposite direction. These should be around lakes and coasts prone to flooding and be labelled as such on state names (e.g. Name of region Floodzone Stage 1).

There should also be the same for dry lake names (such as the Congo lake from TNO) to make it more clear for map-painting

These can be accompanied by canals like how the Qattara canal exists and how dams exists for reclamation area

**Comment by Pcola129** [comment]
done.
